


CREATE TABLE bank_a_transactions (
    bank_specific_account_id character varying(255) NOT NULL,
    transaction_date character varying(255),
    amount character varying(255),
    description character varying(255),
    location_code character varying(255)
);


CREATE TABLE bank_b_transactions (
    bank_specific_account_id character varying(255) NOT NULL,
    transaction_date character varying(255),
    amount character varying(255),
    description character varying(255),
    location_code character varying(255)
);


CREATE TABLE batch_job_execution (
    job_execution_id bigint NOT NULL,
    version bigint,
    job_instance_id bigint NOT NULL,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    status character varying(10),
    exit_code character varying(2500),
    exit_message character varying(2500),
    create_time timestamp without time zone,
    last_updated timestamp without time zone,
    job_configuration_location character varying(2500)
);


CREATE TABLE batch_job_execution_context (
    job_execution_id bigint NOT NULL,
    short_context character varying(2500) NOT NULL,
    serialized_context text
);

ALTER TABLE batch_job_execution ALTER COLUMN job_execution_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME batch_job_execution_job_execution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE batch_job_execution_params (
    job_execution_id bigint NOT NULL,
    parameter_name character varying(100) NOT NULL,
    parameter_type character varying(100) NOT NULL,
    parameter_value character varying(2500),
    identifying character(1) NOT NULL
);


CREATE SEQUENCE batch_job_execution_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 9223372036854775806
    CACHE 1;


CREATE TABLE batch_job_instance (
    job_instance_id bigint NOT NULL,
    version bigint,
    job_name character varying(100),
    job_key character varying(32)
);


ALTER TABLE batch_job_instance ALTER COLUMN job_instance_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME batch_job_instance_job_instance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE SEQUENCE batch_job_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 9223372036854775806
    CACHE 1;

CREATE TABLE batch_step_execution (
    step_execution_id bigint NOT NULL,
    version bigint,
    step_name character varying(100) NOT NULL,
    job_execution_id bigint NOT NULL,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    status character varying(10),
    commit_count bigint,
    read_count bigint,
    filter_count bigint,
    write_count bigint,
    read_skip_count bigint,
    write_skip_count bigint,
    process_skip_count bigint,
    rollback_count bigint,
    exit_code character varying(2500),
    exit_message character varying(2500),
    last_updated timestamp without time zone,
    create_time timestamp without time zone
);

CREATE TABLE batch_step_execution_context (
    step_execution_id bigint NOT NULL,
    short_context character varying(2500) NOT NULL,
    serialized_context text
);


CREATE SEQUENCE batch_step_execution_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 9223372036854775806
    CACHE 1;

ALTER TABLE batch_step_execution ALTER COLUMN step_execution_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME batch_step_execution_step_execution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE customer_mdm_entity (
    id bigint NOT NULL,
    bank_specific_account_id character varying(255),
    unified_customer_id character varying(255)
);

ALTER TABLE customer_mdm_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME customer_mdm_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE fact_transactions (
    id bigint NOT NULL,
    bank_id character varying(255),
    customer_id character varying(255),
    transaction_time timestamp without time zone,
    amount_standard numeric,
    description_standard character varying(255),
    location_code character varying(255),
    transaction_type character varying(255),
    is_valid boolean,
    category character varying(255),
    customer_segment character varying(255)
);

ALTER TABLE fact_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME fact_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY bank_a_transactions
    ADD CONSTRAINT bank_a_transactions_pkey PRIMARY KEY (bank_specific_account_id);

ALTER TABLE ONLY bank_b_transactions
    ADD CONSTRAINT bank_b_transactions_pkey PRIMARY KEY (bank_specific_account_id);

ALTER TABLE ONLY batch_job_execution_context
    ADD CONSTRAINT batch_job_execution_context_pkey PRIMARY KEY (job_execution_id);

ALTER TABLE ONLY batch_job_execution
    ADD CONSTRAINT batch_job_execution_pkey PRIMARY KEY (job_execution_id);

ALTER TABLE ONLY batch_job_instance
    ADD CONSTRAINT batch_job_instance_pkey PRIMARY KEY (job_instance_id);

ALTER TABLE ONLY batch_step_execution_context
    ADD CONSTRAINT batch_step_execution_context_pkey PRIMARY KEY (step_execution_id);

ALTER TABLE ONLY batch_step_execution
    ADD CONSTRAINT batch_step_execution_pkey PRIMARY KEY (step_execution_id);

ALTER TABLE ONLY customer_mdm_entity
    ADD CONSTRAINT customer_mdm_entity_pkey PRIMARY KEY (id);

ALTER TABLE ONLY fact_transactions
    ADD CONSTRAINT fact_transactions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY batch_job_instance
    ADD CONSTRAINT job_inst_un UNIQUE (job_name, job_key);

ALTER TABLE ONLY batch_job_execution_context
    ADD CONSTRAINT job_exec_ctx_fk FOREIGN KEY (job_execution_id) REFERENCES batch_job_execution(job_execution_id);

ALTER TABLE ONLY batch_job_execution
    ADD CONSTRAINT job_exec_inst_fk FOREIGN KEY (job_instance_id) REFERENCES batch_job_instance(job_instance_id);

ALTER TABLE ONLY batch_job_execution_params
    ADD CONSTRAINT job_exec_params_fk FOREIGN KEY (job_execution_id) REFERENCES batch_job_execution(job_execution_id);
