package com.hibersoft.ms.bankcustomer.datamodeling.model;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "FACT_TRANSACTIONS")
@Getter
@Setter
public class FactTransactionEntity {
       // Primary key for the fact table (might be a sequence generated ID or a composite key)
    @Id 
    private Long id; 
    
    private String bankId;
    private String customerId; // The unified/master ID
    private LocalDateTime transactionTime;
    private BigDecimal amountStandard;
    private String descriptionStandard; // Renamed to avoid SQL keyword conflict
    private String locationCode;
    private String transactionType;
    private boolean isValid; // Quality flag

    // Getters and Setters are generated by Lombok

    public boolean getIsValid() {
        return this.isValid;
    }

    public void setIsValid(boolean isValid) {
        this.isValid = isValid;
    }

}
